sudo: required
services:
  - docker
before_install:
  - docker build -t zeeshanlive/react-test -f ./client/dev.Dockerfile ./client

script:
  - docker run -e CI=true zeeshanlive/react-test npm test

after_success:
  - docker build -t zeeshanlive/multi-client ./client
  - docker build -t zeeshanlive/multi-nginx ./nginx
  - docker build -t zeeshanlive/multi-server ./server
  - docker build -t zeeshanlive/multi-worker ./worker
# log in docker
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin


  # Take images push it to docker-hub
  - docker push zeeshanlive/multi-client
  - docker push zeeshanlive/multi-nginx 
  - docker push zeeshanlive/multi-server
  - docker push zeeshanlive/multi-worker
deploy:
  provider: elasticbeanstalk
  region: "eu-west-2"
  app: "nulti-container"
  env: "NultiContainer-env"
  bucket_name: "elasticbeanstalk-eu-west-2-799073789460"
  bucket_path: "docker-multi"
  on:
    branch: master
  access_key_id: 
    secure: $AWS_ACCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"  